services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: people
    ports: [ "5432:5432" ]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10

  api:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/people
      NODE_ENV: production
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy
    ports: [ "3000:3000" ]
    command: sh -c "npm run migrate && npm start"

volumes:
  pgdata:
